# Generated by Django 5.0.8 on 2024-10-19 02:49

import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLogos',
            fields=[
                ('IDImageLogo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageLogo',
        ),
    ]