# Generated by Django 5.0.8 on 2024-10-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_imagelogos_delete_imagelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelogos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
