# Generated by Django 5.0.8 on 2024-10-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_imagelogos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelogos',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
