# Generated by Django 5.0.8 on 2024-10-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_imagelogos_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageLogos',
        ),
    ]
