# Generated by Django 5.0.8 on 2024-08-09 06:02

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('IDCategoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInventario',
            fields=[
                ('IDDetalleInventario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('IDInventario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CantidadMaxima', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('CantidadMinima', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('existencia', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('IDPrecioProducto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FechaPrecio', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('Costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Margen', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Ganancia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('IDProducto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CodigoProducto', models.CharField(max_length=20)),
                ('NombreProducto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('FechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
