# Generated by Django 5.0.8 on 2024-08-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='IDCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase'),
        ),
        migrations.AddField(
            model_name='detalleinventario',
            name='IDInventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='IDCategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.categoria'),
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='IDProducto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precio_producto', to='inventory.producto'),
        ),
        migrations.AddField(
            model_name='detalleinventario',
            name='IDProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto'),
        ),
    ]
