# Generated by Django 5.0.8 on 2024-08-10 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='CantidadMaxima',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='CantidadMinima',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='IDCompra',
        ),
        migrations.AddField(
            model_name='inventario',
            name='IDProducto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidadMinima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.DeleteModel(
            name='DetalleInventario',
        ),
    ]
