# Generated by Django 5.0.8 on 2024-08-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventario_cantidadmaxima_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='existencia',
            new_name='costoEntrada',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='estado',
            new_name='tipoMovimiento',
        ),
        migrations.AddField(
            model_name='inventario',
            name='costoPromedio',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='costoSaldo',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='costoSalida',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='entrada',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='saldoUnidades',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='salida',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
