# Generated by Django 5.0.8 on 2024-08-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventario_costoentrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='costoEntrada',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='costoPromedio',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='costoSaldo',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='costoSalida',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='entrada',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='saldoUnidades',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='salida',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='precioproducto',
            name='Costo',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='precioproducto',
            name='Ganancia',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='precioproducto',
            name='Margen',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='precioproducto',
            name='Precio',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
    ]
