# Generated by Django 5.0.8 on 2024-08-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventario_tipomovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='movement_type',
            field=models.CharField(choices=[('2', 'Entrada por ajuste'), ('3', 'Salida por ajuste')], max_length=1, null=True),
        ),
    ]
