# Generated by Django 5.0.8 on 2024-08-28 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventoryadjustment_type_and_more'),
        ('purchase', '0015_remove_expense_payment_method_and_more'),
        ('sales', '0024_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='IDPurchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchase'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='IDSale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale'),
        ),
    ]
