# Generated by Django 5.0.8 on 2024-10-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventario_idpurchase_inventario_idsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryadjustment',
            name='type',
        ),
    ]
