# Generated by Django 5.0.8 on 2024-10-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_inventoryadjustment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryadjustment',
            name='description',
        ),
    ]
