# Generated by Django 5.0.8 on 2024-08-09 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('IDDepartment', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('IDMunicipality', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('IDDepartment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.department')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('IDClient', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('IDMunicipality', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.municipality')),
            ],
        ),
    ]
