# Generated by Django 5.0.8 on 2024-08-13 01:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_existencia_inventario_costoentrada_and_more'),
        ('purchase', '0004_alter_purchasedetail_idpurchase'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('IDSale', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typeSale', models.BooleanField(default=True)),
                ('typeShipping', models.BooleanField(default=True)),
                ('shippingCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('subTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('IDClient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.client')),
                ('IDCurrency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchase.currency')),
                ('IDPaymentMethod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchase.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('IDSaleDetail', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('subTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('IDProduct', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.producto')),
                ('IDSale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.sale')),
            ],
        ),
    ]
