# Generated by Django 5.0.8 on 2024-08-13 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_saledetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='cost',
        ),
    ]
