# Generated by Django 5.0.8 on 2024-08-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_saledetail_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shippingCost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subTotal',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='subTotal',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
