# Generated by Django 5.0.8 on 2024-08-15 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_discount_alter_sale_shippingcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='salesCode',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.CreateModel(
            name='OnCredit',
            fields=[
                ('IDOnCredit', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('IDSale', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.sale')),
            ],
        ),
    ]
