# Generated by Django 5.0.8 on 2024-08-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_salescode_oncredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='salesCode',
            field=models.CharField(default='no', max_length=10, unique=True),
        ),
    ]
