# Generated by Django 5.0.8 on 2024-08-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_salescode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='salesCode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
