# Generated by Django 5.0.8 on 2024-08-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_sale_salescode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
