# Generated by Django 5.0.8 on 2024-08-15 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_saledetail_date_alter_client_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('IDAccountsReceivable', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.BooleanField(default=True)),
                ('inflow', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('outflow', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('state', models.BooleanField(default=True)),
                ('dateSale', models.DateTimeField(auto_now_add=True)),
                ('IDClient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.client')),
            ],
        ),
        migrations.DeleteModel(
            name='OnCredit',
        ),
    ]
