# Generated by Django 5.0.8 on 2024-08-15 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_accountsreceivable_delete_oncredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='IDSale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
    ]
