# Generated by Django 5.0.8 on 2024-08-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_sale_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsreceivable',
            name='state',
        ),
    ]
