# Generated by Django 5.0.8 on 2024-08-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_accountsreceivable_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isCredit',
            field=models.BooleanField(default=False),
        ),
    ]
