# Generated by Django 5.0.8 on 2024-08-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_accountsreceivable_idsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
