# Generated by Django 5.0.8 on 2024-08-16 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventario_costoentrada_and_more'),
        ('sales', '0017_accountsreceivable_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('IDQuotation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotationCode', models.CharField(max_length=10, unique=True)),
                ('typeShipping', models.BooleanField(default=True)),
                ('shippingCost', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('subTotal', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('0', 'INACTIVO'), ('1', 'ACTIVA'), ('2', 'COMPLETADA')], max_length=1)),
                ('IDClient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.client')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationDetail',
            fields=[
                ('IDQuotationDetail', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('subTotal', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('state', models.BooleanField(default=True)),
                ('IDProduct', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.producto')),
                ('IDQuotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.quotation')),
            ],
        ),
    ]
