# Generated by Django 5.0.8 on 2024-08-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='expirationDate',
            field=models.DateTimeField(null=True),
        ),
    ]
