# Generated by Django 5.0.8 on 2024-08-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_accountsreceivable_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsreceivable',
            name='expirationDate',
            field=models.DateField(null=True),
        ),
    ]
