# Generated by Django 5.0.8 on 2024-08-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_alter_accountsreceivable_expirationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsreceivable',
            name='expirationDate',
        ),
        migrations.AddField(
            model_name='sale',
            name='expirationDate',
            field=models.DateField(null=True),
        ),
    ]
