# Generated by Django 5.0.8 on 2024-09-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_alter_accountsreceivable_idclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
