# Generated by Django 5.0.8 on 2024-09-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_rename_priceproduct_saledetail_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
