# Generated by Django 5.0.8 on 2024-09-10 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_alter_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='IDCurrency',
        ),
    ]
