# Generated by Django 5.0.8 on 2024-09-14 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_alter_sale_date'),
        ('sales', '0043_alter_sale_date_alter_sale_voucher'),
    ]

    operations = [
    ]
