# Generated by Django 5.0.8 on 2024-09-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_merge_20240913_2110'),
        ('sales', '0044_merge_20240913_2131'),
    ]

    operations = [
    ]
