# Generated by Django 5.0.8 on 2024-09-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_merge_20240913_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
