# Generated by Django 5.0.8 on 2024-09-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
