# Generated by Django 5.0.8 on 2024-09-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='isVoucher',
            field=models.BooleanField(default=True),
        ),
    ]
