# Generated by Django 5.0.8 on 2024-09-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_sale_isvoucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
