# Generated by Django 5.0.8 on 2024-09-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_sale_isvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='paymentCode',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
