# Generated by Django 5.0.8 on 2024-09-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_accountsreceivable_paymentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='salesCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
