# Generated by Django 5.0.8 on 2024-09-20 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_alter_sale_date'),
        ('sales', '0050_alter_sale_salescode'),
    ]

    operations = [
    ]
