# Generated by Django 5.0.8 on 2024-09-25 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_alter_expense_state'),
        ('sales', '0052_alter_sale_salescode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='IDPaymentMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='purchase.paymentmethod'),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='voucher',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
