# Generated by Django 5.0.8 on 2024-09-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0056_accountsreceivable_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsreceivable',
            name='voucher',
        ),
    ]
