# Generated by Django 5.0.8 on 2024-09-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0057_remove_accountsreceivable_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='voucher',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
