# Generated by Django 5.0.8 on 2024-10-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0058_accountsreceivable_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
