# Generated by Django 5.0.8 on 2024-10-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_sale_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='IDSD',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
