# Generated by Django 5.0.8 on 2024-10-12 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0061_saledetail_idsd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='IDSD',
        ),
    ]
