# Generated by Django 5.0.8 on 2024-10-15 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0062_remove_saledetail_idsd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='IDSale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.sale'),
        ),
    ]
