# Generated by Django 5.0.8 on 2024-10-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0064_saledetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
