# Generated by Django 5.0.8 on 2024-08-09 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('IDCurrency', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('IDPaymentMethod', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('IDSupplier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('SocialReason', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('IDPurchase', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('IDCurrency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchase.currency')),
                ('IDPaymentMethod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchase.paymentmethod')),
                ('IDSupplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchase.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('IDPurchaseDetail', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('subTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('IDProduct', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.producto')),
                ('IDPurchase', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchase.purchase')),
            ],
        ),
    ]
