# Generated by Django 5.0.8 on 2024-08-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchase_discount_alter_purchase_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='PurchaseCode',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
