# Generated by Django 5.0.8 on 2024-08-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_purchase_purchasecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
