# Generated by Django 5.0.8 on 2024-08-20 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_rename_category_expense_idexpensecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='expense',
            name='IDPaymentMethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.paymentmethod'),
        ),
    ]
