# Generated by Django 5.0.8 on 2024-09-10 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0019_alter_expense_date'),
        ('sales', '0040_remove_sale_idcurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='IDCurrency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
