# Generated by Django 5.0.8 on 2024-09-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_remove_purchase_idcurrency_delete_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='IDPaymentMethod',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor',
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
