# Generated by Django 5.0.8 on 2024-10-15 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_alter_expense_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='IDPurchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchase.purchase'),
        ),
    ]
