# Generated by Django 5.0.8 on 2024-10-15 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0025_expensecategory_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
