# Generated by Django 5.0.8 on 2024-10-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0026_purchasedetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
