# Generated by Django 5.0.8 on 2024-10-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0028_alter_supplier_email_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='SocialReason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ruc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
